name: main

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - 'v*.*.*'

jobs:
  check:
    name: Check rm1asm quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checking
        run: |
          make pre-commit
          make test
